### ISSUE TITLE
Tunnel settings 

### ISSUE THREAD

**Issue by bumbifyllan** [TheSpaghettiDetective/obico-server#654]
hi how do i make the tunnel work again as it worked on old spaghetti detective in ondly open port 3334 on the old what setings should i do to start the tunnel again

**Comment by kennethjiang** [comment]
I doubt this has to do with changing from TSD to Obico as the tunneling was not changed. I suspect the problem was caused by an environment issue. Please go to https://www.obico.io/discord/ to get a speedier help. If it turns out to be a bug, you can reopen this issue with more info so that we know how to reproduce it.
